# Generated by Django 4.1.7 on 2023-03-27 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Auto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("marca", models.CharField(max_length=50)),
                ("modelo", models.CharField(max_length=50)),
                ("color", models.CharField(max_length=50)),
                ("año", models.IntegerField()),
                ("precio", models.IntegerField()),
            ],
        ),
    ]
