# Generated by Django 4.1.7 on 2023-03-28 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("marca", "0001_initial"),
        ("auto", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="auto",
            name="created_on",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="auto",
            name="deleted_on",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="auto",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="auto",
            name="modified_on",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="auto",
            name="marca",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="marca.marca"
            ),
        ),
    ]
