# Generated by Django 4.1.7 on 2023-04-03 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("marca", "0001_initial"),
        ("auto", "0002_auto_created_on_auto_deleted_on_auto_is_active_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auto",
            name="marca",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="marca",
                to="marca.marca",
            ),
        ),
    ]
